version: '3'

services:
  netdata:
    image: netdata/netdata:latest
    container_name: netdata
    restart: always
    ports:
      - "19999:19999"
    networks:
      - monitoring

  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    restart: always
    ports:
      - "9093:9093"
    volumes:
      - alertmanager-data:/etc/alertmanager
    environment:
      - ALERTMANAGER_NOTIFICATION_EMAILS=youremail@example.com
    networks:
      - monitoring

networks:
  monitoring:

volumes:
  alertmanager-data:

